FROM node:18 AS build

WORKDIR /app
COPY Frontend/lms/package*.json ./
RUN npm install
COPY Frontend/lms .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist

EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
